/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsInjuriesRouteImport } from './routes/sports-injuries'
import { Route as ShoulderArthroscopyRouteImport } from './routes/shoulder-arthroscopy'
import { Route as KneeSurgeryRouteImport } from './routes/knee-surgery'
import { Route as JointReplacementRouteImport } from './routes/joint-replacement'
import { Route as FractureCareRouteImport } from './routes/fracture-care'
import { Route as FootAnkleConditionsRouteImport } from './routes/foot-ankle-conditions'
import { Route as IndexRouteImport } from './routes/index'

const SportsInjuriesRoute = SportsInjuriesRouteImport.update({
  id: '/sports-injuries',
  path: '/sports-injuries',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoulderArthroscopyRoute = ShoulderArthroscopyRouteImport.update({
  id: '/shoulder-arthroscopy',
  path: '/shoulder-arthroscopy',
  getParentRoute: () => rootRouteImport,
} as any)
const KneeSurgeryRoute = KneeSurgeryRouteImport.update({
  id: '/knee-surgery',
  path: '/knee-surgery',
  getParentRoute: () => rootRouteImport,
} as any)
const JointReplacementRoute = JointReplacementRouteImport.update({
  id: '/joint-replacement',
  path: '/joint-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const FractureCareRoute = FractureCareRouteImport.update({
  id: '/fracture-care',
  path: '/fracture-care',
  getParentRoute: () => rootRouteImport,
} as any)
const FootAnkleConditionsRoute = FootAnkleConditionsRouteImport.update({
  id: '/foot-ankle-conditions',
  path: '/foot-ankle-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foot-ankle-conditions': typeof FootAnkleConditionsRoute
  '/fracture-care': typeof FractureCareRoute
  '/joint-replacement': typeof JointReplacementRoute
  '/knee-surgery': typeof KneeSurgeryRoute
  '/shoulder-arthroscopy': typeof ShoulderArthroscopyRoute
  '/sports-injuries': typeof SportsInjuriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foot-ankle-conditions': typeof FootAnkleConditionsRoute
  '/fracture-care': typeof FractureCareRoute
  '/joint-replacement': typeof JointReplacementRoute
  '/knee-surgery': typeof KneeSurgeryRoute
  '/shoulder-arthroscopy': typeof ShoulderArthroscopyRoute
  '/sports-injuries': typeof SportsInjuriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foot-ankle-conditions': typeof FootAnkleConditionsRoute
  '/fracture-care': typeof FractureCareRoute
  '/joint-replacement': typeof JointReplacementRoute
  '/knee-surgery': typeof KneeSurgeryRoute
  '/shoulder-arthroscopy': typeof ShoulderArthroscopyRoute
  '/sports-injuries': typeof SportsInjuriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foot-ankle-conditions'
    | '/fracture-care'
    | '/joint-replacement'
    | '/knee-surgery'
    | '/shoulder-arthroscopy'
    | '/sports-injuries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foot-ankle-conditions'
    | '/fracture-care'
    | '/joint-replacement'
    | '/knee-surgery'
    | '/shoulder-arthroscopy'
    | '/sports-injuries'
  id:
    | '__root__'
    | '/'
    | '/foot-ankle-conditions'
    | '/fracture-care'
    | '/joint-replacement'
    | '/knee-surgery'
    | '/shoulder-arthroscopy'
    | '/sports-injuries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FootAnkleConditionsRoute: typeof FootAnkleConditionsRoute
  FractureCareRoute: typeof FractureCareRoute
  JointReplacementRoute: typeof JointReplacementRoute
  KneeSurgeryRoute: typeof KneeSurgeryRoute
  ShoulderArthroscopyRoute: typeof ShoulderArthroscopyRoute
  SportsInjuriesRoute: typeof SportsInjuriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports-injuries': {
      id: '/sports-injuries'
      path: '/sports-injuries'
      fullPath: '/sports-injuries'
      preLoaderRoute: typeof SportsInjuriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoulder-arthroscopy': {
      id: '/shoulder-arthroscopy'
      path: '/shoulder-arthroscopy'
      fullPath: '/shoulder-arthroscopy'
      preLoaderRoute: typeof ShoulderArthroscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knee-surgery': {
      id: '/knee-surgery'
      path: '/knee-surgery'
      fullPath: '/knee-surgery'
      preLoaderRoute: typeof KneeSurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joint-replacement': {
      id: '/joint-replacement'
      path: '/joint-replacement'
      fullPath: '/joint-replacement'
      preLoaderRoute: typeof JointReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fracture-care': {
      id: '/fracture-care'
      path: '/fracture-care'
      fullPath: '/fracture-care'
      preLoaderRoute: typeof FractureCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foot-ankle-conditions': {
      id: '/foot-ankle-conditions'
      path: '/foot-ankle-conditions'
      fullPath: '/foot-ankle-conditions'
      preLoaderRoute: typeof FootAnkleConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FootAnkleConditionsRoute: FootAnkleConditionsRoute,
  FractureCareRoute: FractureCareRoute,
  JointReplacementRoute: JointReplacementRoute,
  KneeSurgeryRoute: KneeSurgeryRoute,
  ShoulderArthroscopyRoute: ShoulderArthroscopyRoute,
  SportsInjuriesRoute: SportsInjuriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
